[workspace]
authors = ["Alex Sopio <alexander.linus.sopio@cern.ch>"]
channels = ["conda-forge"]
name = "root-rust-vortex"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
build = "cargo build --release"
clean = "cargo clean"
test = "cargo test"
build-py = { cmd = "maturin develop --release", cwd = "root-vortex-py" }
cli = "cargo run -p root-vortex-cli --release --"

[dependencies]
rust = ">=1.78"
maturin = ">=1.0,<2.0"
python = ">=3.9,<3.14"
clangdev = "*"
gcc = "*"
sysroot_linux-64 = "2.34.*"
pip = ">=26.1.1,<27"

[activation.env]
LIBCLANG_PATH = "$CONDA_PREFIX/lib"
CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER = "x86_64-conda-linux-gnu-cc"
RUSTFLAGS = "-C link-arg=-fuse-ld=bfd -C link-arg=--sysroot=$CONDA_PREFIX/x86_64-conda-linux-gnu/sysroot"
